# Generated by Django 2.2.13 on 2020-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hghghg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hghghg',
        ),
    ]
